### ISSUE TITLE
Ist Laravel vom Tisch?

### ISSUE THREAD

**Issue by BlueTeck** [DZCP-Community/Core-DZCP-Beta#19]
Hey Ihr,

ist der Laravel Ansatz (https://github.com/DZCP-Community/DZCP-2.0) dann wieder vom Tisch?
Und wird dies die zukünftige Version?

Grüße,
Timo

**Comment by hammermaps** [comment]
Aktuell wird dieses Projekt nicht verfolgt.



 Von:   Timo <notifications@github.com> 
 An:   DZCP-Community/Core-DZCP-Beta <Core-DZCP-Beta@noreply.github.com> 
 Kopie:   Subscribed <subscribed@noreply.github.com> 
 Gesendet:   04.10.2017 22:35 
 Betreff:   [DZCP-Community/Core-DZCP-Beta] Ist Laravel vom Tisch? (#19) 


Hey Ihr, 
ist der Laravel Ansatz (https://github.com/DZCP-Community/DZCP-2.0) dann wieder vom Tisch?
 Und wird dies die zukünftige Version? 
Grüße,
 Timo

**Comment by BlueTeck** [comment]
Okay, schade.
