### ISSUE TITLE
ABWESENHEIT EDITIEREN (Datum)

### ISSUE THREAD

**Issue by 65DirtyHarry** [DZCP-Community/Core-DZCP-Beta#21]
Uuuuuuups das hätte nicht passieren ....

Debug Log: ( 6 Einträge )
--
File/Code:Action/Msg:"HINWEIS:' /away/index.php '""Line:"233" => Undefined index: m""HINWEIS:' /away/index.php '""Line:"233" => Undefined index: t""HINWEIS:' /away/index.php '""Line:"233" => Undefined index: j""HINWEIS:' /away/index.php '""Line:"234" => Undefined index: monat""HINWEIS:' /away/index.php '""Line:"234" => Undefined index: tag""HINWEIS:' /away/index.php '""Line:"234" => Undefined index: jahr" | File/Code: | Action/Msg: | "HINWEIS:' /away/index.php '" | "Line:"233" => Undefined index: m" | "HINWEIS:' /away/index.php '" | "Line:"233" => Undefined index: t" | "HINWEIS:' /away/index.php '" | "Line:"233" => Undefined index: j" | "HINWEIS:' /away/index.php '" | "Line:"234" => Undefined index: monat" | "HINWEIS:' /away/index.php '" | "Line:"234" => Undefined index: tag" | "HINWEIS:' /away/index.php '" | "Line:"234" => Undefined index: jahr"
File/Code: | Action/Msg:
"HINWEIS:' /away/index.php '" | "Line:"233" => Undefined index: m"
"HINWEIS:' /away/index.php '" | "Line:"233" => Undefined index: t"
"HINWEIS:' /away/index.php '" | "Line:"233" => Undefined index: j"
"HINWEIS:' /away/index.php '" | "Line:"234" => Undefined index: monat"
"HINWEIS:' /away/index.php '" | "Line:"234" => Undefined index: tag"
"HINWEIS:' /away/index.php '" | "Line:"234" => Undefined index: jahr"

**Comment by hammermaps** [comment]
Ich schau später in die richtige log dateilweise :)

**Comment by hammermaps** [comment]
Bezieht sich auf Version 1.6 -> https://github.com/DZCP-Community/DZCP-1.6/commit/9f39bdb19b554dab409f6ceec652ed7c09fbc05e
